# A Secret holds sensitive data like usernames and passwords (base64-encoded)
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret  # This name is used by Deployments to reference the secret
type: Opaque           # 'Opaque' is the most common type for user-defined key-value secrets
data:
  mongo-user: bW9uZ291c2Vy           # base64-encoded value of 'mongouser'
  mongo-password: bW9uZ29wYXNzd29yZA==  # base64-encoded value of 'mongopassword'
